"""add service and ingestion tables

Revision ID: 2ddc1db3435e
Revises: 9f1e0097ce52
Create Date: 2026-09-19 17:36:15.318855

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ddc1db3435e"
down_revision: str | Sequence[str] | None = "9f1e0097ce52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "environment",
            sa.Enum("DEVELOPMENT", "STAGING", "PRODUCTION", name="environment"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_services_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("organization_id", "name", name="uq_services_organization_id_name"),
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("deployed_by", sa.String(length=255), nullable=False),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_deployments_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployments")),
    )
    op.create_index(
        "ix_deployments_service_time", "deployments", ["service_id", "deployed_at"], unique=False
    )
    op.create_table(
        "log_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", name="log_level"),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=4000), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_log_events_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_log_events")),
    )
    op.create_index(
        "ix_log_events_service_time", "log_events", ["service_id", "recorded_at"], unique=False
    )
    op.create_table(
        "metric_samples",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("metric_name", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_metric_samples_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_samples")),
    )
    op.create_index(
        "ix_metric_samples_service_metric_time",
        "metric_samples",
        ["service_id", "metric_name", "recorded_at"],
        unique=False,
    )
    op.drop_constraint(op.f("organizations_name_key"), "organizations", type_="unique")
    op.create_unique_constraint(op.f("uq_organizations_name"), "organizations", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_organizations_name"), "organizations", type_="unique")
    op.create_unique_constraint(
        op.f("organizations_name_key"),
        "organizations",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index("ix_metric_samples_service_metric_time", table_name="metric_samples")
    op.drop_table("metric_samples")
    op.drop_index("ix_log_events_service_time", table_name="log_events")
    op.drop_table("log_events")
    op.drop_index("ix_deployments_service_time", table_name="deployments")
    op.drop_table("deployments")
    op.drop_table("services")
    # ### end Alembic commands ###
